### ISSUE TITLE
Using jsonDir property results in a merged JSON file which is never refreshed

### ISSUE THREAD

**Issue by arjunjh10** [gkushang/cucumber-html-reporter#103]
Hello,
I have come across a problem where I am using the `jsonDir` to provide more than 1 JSON file inputs to my cucumber reporter to generated a consolidated HTML report for my json files.

What has been noticed is that upon each run the html report does not get refreshed but more results get added to the file. for example:
Upon first run - 2 scenarios run in parallel =>> report generates mentioning those 2 scenarios
Upon 2nd run - same scenarios run in parallel =>> report appends the result html with 2 of the same scenarios' data, meaning we now have duplicate data instead of a fresh report.
![screen shot 2017-08-07 at 1 52 28 pm](https://user-images.githubusercontent.com/7624561/29009470-aea4a1ac-7b77-11e7-857d-74944f38289b.png)

Could this be resolved? Thanks!

**Comment by erikgk** [comment]
We delete all the report data and create a fresh result every build in our build pipeline. The json files also get converter to junit xml files which get processed by the build server to keep track of test-trends. So simply clean out the report dir in your build process is an approach.

**Comment by arjunjh10** [comment]
Yeah, sounds like a plan. 
But this behaviour definitely seems like a bug in report generation to me.
