### ISSUE TITLE
Features subsection cannot be expanded in hierarchy template

### ISSUE THREAD

**Issue by kozhevnikov** [gkushang/cucumber-html-reporter#112]
Test project: https://github.com/kozhevnikov/cucumber-html-reporter-bug
Test output: https://github.com/kozhevnikov/cucumber-html-reporter-bug/blob/master/docs/test.gif

**Comment by gkushang** [comment]
@kozhevnikov 

Which version are you using?

**Comment by kozhevnikov** [comment]
Still affects the latest 3.0.4
