### ISSUE TITLE
Using the hierarchy template, all "+ Show error" links toggle the errors registered in the first suite

### ISSUE THREAD

**Issue by damonpam** [gkushang/cucumber-html-reporter#119]
It seems that the errors linked on each scenario do not depend on the suite where they occur. All the errors are linked to the first suite (suite 0).

![hierarchy-error](https://user-images.githubusercontent.com/12949398/31662679-ae8c94e0-b33f-11e7-858d-986890d26534.PNG)

**Comment by gkushang** [comment]
@damonpam 

This should have been fixed with the latest release @4.0.3. Please reopen the issue if you are still facing it.
