### ISSUE TITLE
Unable to produce report

### ISSUE THREAD

**Issue by telangn** [gkushang/cucumber-html-reporter#120]
Hi @gkushang 
1. I did the npm install of the package
2. Edited the index.js for the options you wrote below.
3. Did a: "node index.js", I get an error - "function reporter.generate is not a function"
4. Ran cucumber jvm, and produced the json report, still nothing happened. 

Am I missing something? why is reporter.generate not being recognized?
Thanks!
Ninad

'use strict';

var reporter = require('cucumber-html-reporter');

var options = {
 theme: 'bootstrap',
 jsonFile: '/home/ninad/eclipse-workspace/Reports/cucumber-report.json',
 output: '/home/ninad/eclipse-workspace/Reports',
 reportSuiteAsScenarios: true,
 launchReport: true
};

reporter.generate(options);

function generateReport(options) {
    return reporter.generate(options);
}

module.exports = {
    generate: generateReport
};

**Comment by Sylhare** [comment]
Hi @telangn,

What did you do to make it work? I am having the same issue.

**Comment by telangn** [comment]
From my index.js file
`'use strict';

var reporter = require('./lib/reporter');
var options = {
 theme: 'bootstrap',
 jsonFile: '/home/ninad/eclipse-workspace/Reports/cucumber-report.json',
 output: '/home/ninad/eclipse-workspace/Reports/cucumber_report.html',
 reportSuiteAsScenarios: true,
 storeScreenshots: true,
 screenshotsDirectory: '/home/ninad/eclipse-workspace/Reports/html/'
}


generateReport(options);

function generateReport(options) {
    return reporter.generate(options);
}

module.exports = {
    generate: generateReport
};
`

**Comment by Sylhare** [comment]
Thanks, it's now working for me, addition to that, I had made a mistake with the links (relative vs absolute link to the file).
