### ISSUE TITLE
Link Show Errors is UX unfriendly

### ISSUE THREAD

**Issue by znevrly** [gkushang/cucumber-html-reporter#121]
Hi,
first of all, thx for nice work! 

Bootstrap theme generally looks good except one major thing. Link Show Error. 
1. It's too small. It would be great if it can be clickable to large panel (CSS modal window maybe).  
2. It's would be great if code highlighting (json) works in panel.

<img width="272" alt="assertion_error" src="https://user-images.githubusercontent.com/1698263/32243974-566186ca-be77-11e7-9126-695a9c2557fd.png">

**Comment by telangn** [comment]
Sir, as you have gotten this node module to work, can you please help me? My issue is #120 
I cannot get it to simply work. I get the error TypeError: reporter.generate is not a function
when I update index.js with my options and then pass them in. 
Many thanks.

**Comment by telangn** [comment]
Nevermind, I figured it out

**Comment by gkushang** [comment]
Opening a model to render the error is a good idea.

**Comment by gkushang** [comment]
Marking this issue as a Feature Request

**Comment by znevrly** [comment]
Would be great if report supports custom template.

**Comment by znevrly** [comment]
This can be closed because is subset of https://github.com/gkushang/cucumber-html-reporter/issues/147

**Comment by gkushang** [comment]
Errors or info can be viewed in Overlay Modal. Released with the version cucumber-html-reporter@4.0.3
