### ISSUE TITLE
storeScreenshots option in config not creating screen shots

### ISSUE THREAD

**Issue by Debananda** [gkushang/cucumber-html-reporter#123]
Below is the config i have used. This config is not giving me screenshots

**package.json**
"devDependencies": {
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "cucumber": "^3.1.0",
    "cucumber-html-reporter": "^3.0.4",
    "protractor": "^5.2.0",
    "protractor-cucumber-framework": "^4.1.1"
  },

**reporter config** 
var reporter = require('cucumber-html-reporter');

var options = {
    theme: 'bootstrap',
    jsonFile: 'test/reports/cucumber_report.json',
    output: 'test/reports/cucumber_report.html',
    ignoreBadJsonFile: true,
    reportSuiteAsScenarios: true,
    launchReport: true,
    sscreenshotsDirectory: 'test/screenshots/',
    storeScreenshots: true,
    metadata: {
        "App Version":"0.3.2",
        "Test Environment": "STAGING",
        "Browser": "Chrome  54.0.2840.98",
        "Platform": "Windows 10",
        "Parallel": "Scenarios",
        "Executed": "Remote"
    }
};

reporter.generate(options);

**Comment by bjohnso5** [comment]
If this is verbatim to your config, you have a typo (double leading s): `sscreenshotsDirectory: 'test/screenshots/',`

**Comment by Debananda** [comment]
@bjohnso5 : That's a typo mistake. but its not working for me. How ever I have make a hook for After step to get it working. not sure if that is the way to achieve screenshots

var {defineSupportCode} = require('cucumber');

defineSupportCode(function ({After}) {
    After(function (scenario) {
        const attach = this.attach; 
        return browser.takeScreenshot().then(function (png) {
            const decodedImage = new Buffer(png, "base64");
            return attach(decodedImage, "image/png");
        });
    });
});

**Comment by navalkgupta** [comment]
There is ready example with similar libraries integrated in project "protractor-cucumber-tests" on GitHub, have a look at it for your reference as it generates html report with screenshot.

**Comment by gkushang** [comment]
For integration with Protractor, please take a look at the example https://github.com/igniteram/protractor-cucumber-typescript/blob/master/config/config.ts#L39-L41
