### ISSUE TITLE
Attach screenshot to failed step not to After hook

### ISSUE THREAD

**Issue by sisbilir** [gkushang/cucumber-html-reporter#124]
I'm using

 "cucumber": "^3.2.0",
    "cucumber-html-reporter": "^3.0.4",
    "protractor": "^5.2.1",
    "protractor-cucumber-framework": "^4.1.1"

I attach screenshot for failed test cases in after hook. In html report after is displayed as a step and screenshot is displayed under after step. Is there a way to attach screenshot to failed step like displayed in samples? 

![loginerror](https://user-images.githubusercontent.com/21352479/34167905-1be29af6-e4b1-11e7-9538-2a9b1c143204.png)

There is also a similar query for what I want to achieve:
https://stackoverflow.com/questions/45080422/cucumber-attach-screenshot-to-stepresult

**Comment by kotoj** [comment]
@sisbilir could you please provide json which contains screenshot in "After" step?

**Comment by sisbilir** [comment]
Hi @kotoj 
Please see the file. 

[cucumber_report.txt](https://github.com/gkushang/cucumber-html-reporter/files/1600558/cucumber_report.txt)

**Comment by gkushang** [comment]
@sisbilir the reporter would show the Screenshot link in the failed STEP if you capture screenshot in the STEP itself. In this case, and also in the JSON you have provided, the Screenshot is captured at the AFTER step and thus it shows in the AFTER step. 

On the example shown in this repository, it attaches a report to the STEPS. Please take a look at https://github.com/gkushang/cucumber-html-reporter/blob/develop/test/features/step_definitions/stepDefs.js#L36-L40 

Please reopen the issue if you have any more suggestions.
