### ISSUE TITLE
Cannot generate report due an error with Trim()

### ISSUE THREAD

**Issue by vhugogarcia** [gkushang/cucumber-html-reporter#125]
Hello friends,

I'm experiencing an issue when the tests finished to run successfully or no. When it is trying to generate the HTML report, I get this message:

`/Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/node_modules/cucumber/lib/cucumber/runtime/event_broadcaster.js:30
process.nextTick(function(){ throw error; }); // prevent swallow by unhandled rejection
^

TypeError: node_modules/selenium-cucumber-js/runtime/world.js:191 Cannot read property 'trim' of undefined
at sanitize (/Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/node_modules/cucumber-html-reporter/lib/reporter.js:27:21)
at generateReport (/Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/node_modules/cucumber-html-reporter/lib/reporter.js:52:24)
at Object.generate (/Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/node_modules/cucumber-html-reporter/lib/reporter.js:419:9)
at Object.generateReport [as generate] (/Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/node_modules/cucumber-html-reporter/index.js:30:21)
at /Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/runtime/world.js:207:22
at process._tickCallback (internal/process/next_tick.js:150:11)`

Do you know what library or setup is missing?

Once again, I would like to say THANK YOU for this amazing library.

**Comment by gkushang** [comment]
This library reads the JSON supplied by the framework. If there is any undefined value in the JSON, then it must be handled well in this library. Can you share your JSON or object which is undefined?

**Comment by EstherSalinas** [comment]
Hello @vhugogarcia,
I had the same issue.
In my case was because I had not defined "name" in options, in the index.js file.
I fixed it in /node_modules/cucumber-html-reporter/lib/reporter.js:27:21
adding this condition:

 var sanitize = function (name, find) {
        var unsafeCharacters = find || /[\/\\\|:"\*\?<>]/g;
        **if (name !== undefined) {**
            name = name.trim().replace(unsafeCharacters, '_');
        **}**   
        return name;
    };
@gkushang Do you think it is right? If it is I would like to contribute and upload the code.

**Comment by vhugogarcia** [comment]
Hello @gkushang  and @EstherSalinas ,

I was able to fix the issue, the issue was due the .html file was missing from the reports folder and for instance it was generating that error. 

Thanks for your help.

It is good to know the same error occurs on different ways, probably there is a way to return a more verbal error based if a file is missing or something else to differentiate them.

**Comment by gkushang** [comment]
@EstherSalinas 

Sorry for getting late on this. Please go ahead and PR your solution. Thank you for your contributions!
