### ISSUE TITLE
Bootstrap template: Pie chart UI bug (failed feature)

### ISSUE THREAD

**Issue by Sylhare** [gkushang/cucumber-html-reporter#127]
Allo,

While using the report generator, I found a bug using the bootstrap template. When a feature fails, the pie chart (does too). The failed pie is not rendered well:
![image](https://user-images.githubusercontent.com/20642750/35168102-c0681d9e-fd25-11e7-8e0e-345ff4df00ab.png)

Or at list it is not like when the feature pass the cucumber tests:
![image](https://user-images.githubusercontent.com/20642750/35168128-d2d1b54e-fd25-11e7-87b5-b1008857d78a.png)

I guess that must be in the template, I will look in the code if I see something.

**Comment by Sylhare** [comment]
So It's the path in the svg that is not the same on the two pie chart. When I use the path of the green pie, it makes the red one look normal.

The faulty red svg path:
```html
<path fill="#a33e3b" stroke-width="1" stroke="#a33e3b" d="M334,136.28L334,151.08A74,59.2,0,0,1,186,151.08L186,136.28A74,59.2,0,0,0,334,136.28"></path>
```

The good green svg path:
```html
<path d="M334,112.6L334,127.39999999999999A74,59.2,0,0,1,186,127.4L186,112.6A74,59.2,0,0,0,334,112.6" stroke="#458a45" stroke-width="1" fill="#458a45"></path>
```

But I have no idea where to correct that in this repository.

**Comment by newcat** [comment]
Quick&Dirty: Comment out [these](https://github.com/gkushang/cucumber-html-reporter/blob/61c7f3dd1b65e0de64f32af5959ec9408df16569/templates/_common/bootstrap.hierarchy/piechart.js#L29-L36) lines.

**Comment by Sylhare** [comment]
Thanks, however I would need to have the files locally (I was using it as a module through npm).

I will just let it like that while waiting, that's an even greater motivation to make the "failed test" pass. 😃

**Comment by newcat** [comment]
> that's an even greater motivation to make the "failed test" pass.
I wouldn't rely on that; had that bug on 100% passing tests too 😒 
However I don't think there is an elegant way to fix the problem when using it as a npm module. Just wondering what causes the bug though, and since it is an official Google library I wouldn't assume the bug to be in there (altough of course there is a slight chance). Maybe there is a problem when calculating the percentage and the calculated value is >100% or something like there (just speculation though).

**Comment by gkushang** [comment]
@Sylhare If you are referring to the Broken PieChart when test fails, it is actually as desinged. When test breaks, pie chart also breaks in RED. Or, breaks to show any gaps like, Peding, Skipped etc. (Visual presentation along with the Colors)

In Happy case, it does not break and renders in GREEN.

Does it answer?

**Comment by Sylhare** [comment]
Hi @gkushang 

I thought the big RED piechart (The one written only "failed" on the side, not the broken down one that shows the different status, failed, pass, pending, ..) should have been like the big GREEN piechart.

However here you can see that the top of the RED piechart is like like 10px up the shadow side (darker red) of the pie which make it look a bit wrong compared to the GREEN one where the circle on top is next to its darker green side shadow.

It really feels like something is off on the RED failed one.

**Comment by gkushang** [comment]
@Sylhare The RED only pie-chart is as per `exploded` design of Google's pie-chart, where it visually shows tests are broken (exploded), whereas the GREEN pie-chart in-place (not exploded).

**Comment by Sylhare** [comment]
Oh ok, that's a bit strange. Well I guess it's not a bug then eheh.

**Comment by SantiagoMontiel** [comment]
Quick&Dirty Solution. Add these lines in: 
\templates\_common\bootstrap.hierarchy\piechart.js since line 22
@rudemex tx! 

```
var options = {
        width: '100%',
        height: 240,
        title: title,
        is3D: true,
        colors: ['#5cb85c', '#d9534f', '#999', '#5bc0de', '#428bca', '#f0ad4e'],
        fontSize: '13',
        fontName: '"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif',
        slices: {
		  1: {offset: 0.4},
		  2: {offset: 0.4},
		  3: {offset: 0.4},
		  4: {offset: 0.4},
		  5: {offset: 0.4},
		  6: {offset: 0.4}
		},
        titleTextStyle: {
            fontSize: '13',
            color: '#5e5e5e'
        }
    };
	
	if (chartData.failed && total === 1){	
		options.slices = {
		  1: {offset: 0.0},
		  2: {offset: 0.0},
		  3: {offset: 0.0},
		  4: {offset: 0.0},
		  5: {offset: 0.0},
		  6: {offset: 0.0}
		};
	}
```

**Comment by rudemex** [comment]
@SantiagoMontiel of nothing, son.
