### ISSUE TITLE
Supporting HTML tag in screenshot embeddings?

### ISSUE THREAD

**Issue by xywang68** [gkushang/cucumber-html-reporter#129]
In order to avoid a huge cucumber-result.json file, instead of embedding the screenshot image as base64 data, I want to attach a HTML tag sting like <img>. I am able to attach the tag, but the cucumber-html-reporter is not showing.
Am I not doing this correctly? Otherwise can this be supported?

Here is my code in hooks.js:
`      var html_tag = '<img src="pulpitrock.jpg" alt="Mountain View">';
      scenario.attach(Buffer.from(html_tag, 'utf-8'), 'text/html');
`

Here is the cucumber result JSON after run:
`            "embeddings": [
              {
                "data": "PGltZyBzcmM9InB1bHBpdHJvY2suanBnIiBhbHQ9Ik1vdW50YWluIFZpZXciPg==",
                "mime_type": "text/html"
              }
            ],
`
which the data can be base64 decoded back to the original html_tag string.

**Comment by xywang68** [comment]
Hi, I subsequently made a small update in the lib/reporter.js with the following code and it seems to work:
                            if (embeddingType === 'text/plain' || embeddingType === 'text/html') {
                                var decoded = new Buffer(embedding.data, 'base64').toString('ascii');
`
                                if (!step.text) {
                                    step.text = decoded;
                                } else {
                                    step.text = step.text.concat('<br>' + embedding.data);
                                }
                            } else if... (the rest of the code omitted)
`

**Comment by xywang68** [comment]
Here is the git diff. If this looks OK to you I can submit a PR.

$ git diff lib/reporter.js
warning: LF will be replaced by CRLF in lib/reporter.js.
The file will have its original line endings in your working directory.
diff --git a/lib/reporter.js b/lib/reporter.js
index a4b7320..1318918 100755
--- a/lib/reporter.js
+++ b/lib/reporter.js
@@ -220,9 +220,11 @@ var generateReport = function (options) {
                                 embeddingType = embedding.media.type;
                             }

-                            if (embeddingType === 'text/plain') {
+                            if (embeddingType === 'text/plain' || embeddingType === 'text/html') {
+                                var decoded = new Buffer(embedding.data, 'base64').toString('ascii');
+
                                 if (!step.text) {
-                                    step.text = embedding.data;
+                                    step.text = decoded;
                                 } else {
                                     step.text = step.text.concat('<br>' + embedding.data);
                                 }

**Comment by gkushang** [comment]
@xywang68 thanks for looking into it. Please submit a PR

**Comment by xywang68** [comment]
@gkushang , I tried to submit a branch to your git but got access denied. Can you grant permission for me to submit a branch? Or is there another way you prefer me to do?

**Comment by gkushang** [comment]
Hi @xywang68 - You'd not need to push the branch to the Origin. Please [fork](https://help.github.com/articles/fork-a-repo/) a repository, and submit a PR from your forked.

**Comment by xywang68** [comment]
@gkushang, created PR[#132](https://github.com/gkushang/cucumber-html-reporter/pull/132).

**Comment by gkushang** [comment]
Thanks for the PR. All set!
