### ISSUE TITLE
Incorrect time of steps

### ISSUE THREAD

**Issue by IvanNaumenko** [gkushang/cucumber-html-reporter#130]
Hey, after updating of cucumber to 4.0 cucumber-html-reporter shows incorrect timings for steps
![cucumber-html](https://user-images.githubusercontent.com/32741530/35732538-69567372-0822-11e8-9f6c-18a3b35ba590.jpg)

And Junit report, which generated from cucumber.json

![cucumber-j-unit](https://user-images.githubusercontent.com/32741530/35732559-80f34af0-0822-11e8-9290-886cc2b88d90.jpg)

**Comment by gkushang** [comment]
Issue is fixed and released with the version@4.0.0
