### ISSUE TITLE
cucumber-html-reporter unplugged!

### ISSUE THREAD

**Issue by myie-fnorton** [gkushang/cucumber-html-reporter#134]
Just wanted to let you know that I have built an unplugged, containerised wrapper for your excellent reporter, so that it can be used standalone with non-JavaScript Cucumber-style testing tools such as [Godog](https://github.com/DATA-DOG/godog).

It's at https://github.com/myie/cucumber-html-reporter

**Comment by gkushang** [comment]
@myie-fnorton this is awesome! I would like to know more about it 👍
