### ISSUE TITLE
Making this reporter work with WebdriverIO

### ISSUE THREAD

**Issue by javacoldbrew** [gkushang/cucumber-html-reporter#136]
How would you make this work with WebdriverIO? 

When I try to make the json file using:

cucumber-js ./tests/features -r ./tests/steps -f json:./reports/cucumber/cucumber_report.json

I get an error saying that the steps are undefined/skipped.

But they work when I run wdio and wdio-cucumber-reporter says all the tests pass.

**Comment by cgungaloo** [comment]
Im getting the same issue too. The project uses wdio commands to run, it would be great if the html reports could be generated from there rather than having to use the cucumber command.

**Comment by gkushang** [comment]
@javacoldbrew 

Thanks for reporting. Would you please provide the sample JSON file to reproduce the issue? Please reopen the issue if you're still facing.
