### ISSUE TITLE
General support for external files 

### ISSUE THREAD

**Issue by Gahen** [gkushang/cucumber-html-reporter#138]
Hey! Thanks for a great tool.

I would be nice to have generic support for any kind of file attachments. As with the images and other file types this lib currently support it will be handy to allow for other kind of filetypes to be attached for later review.

We made a PR (https://github.com/gkushang/cucumber-html-reporter/pull/137) that achieve this by making a generic "download file" link using the base64 data and the mime type information. Let me know if it's OK to merge or you need some changes to have it merged. It also addresses https://github.com/gkushang/cucumber-html-reporter/issues/111 although we can remove that part if you are not OK with changing the template.

**Comment by gkushang** [comment]
@Gahen 

All set. PR is merged and released with the version 4.0.3
