### ISSUE TITLE
Missing icons for skipped testes 

### ISSUE THREAD

**Issue by filepi** [gkushang/cucumber-html-reporter#139]
The error happes when json is this way

"status": "skipped"

However when I edit to make this way

  "result": {			
			"status": "skipped"
		}

It works perfectly

**Comment by filepi** [comment]
![missing_icons](https://user-images.githubusercontent.com/3999024/38511936-1d6f8144-3c00-11e8-9493-661d03d55252.png)

**Comment by gkushang** [comment]
@filepi 

Thanks for reporting! are you still seeing the issue? If so, please reopen the issue and provide us with reproducible steps.
