### ISSUE TITLE
Pie Charts Do Not Show Undefined Scenarios

### ISSUE THREAD

**Issue by Qxcl** [gkushang/cucumber-html-reporter#160]
Version 4.0.4 is missing the Undefined slice in the pie charts.

I suspect this was caused by `return element.notdefined++;` changing to `return element.undefined++;` in this pull request:
https://github.com/gkushang/cucumber-html-reporter/pull/155/files#diff-7744650016d52918f79696c96d468795R299

**Comment by DesHorsley** [comment]
We're seeing the same thing, it seems like features that contain only undefined steps are being counted as passing.

**Comment by eiszfuchs** [comment]
I struggled with Github's UI yet again, but I tried fixing this issue. 🙈
