### ISSUE TITLE
Can the screenshots generated for passed steps in the features?

### ISSUE THREAD

**Issue by gnaneswarreddy** [gkushang/cucumber-html-reporter#176]
Can the screenshots generated for passed steps in the features? Trying to generate screenshots for passed steps

**Comment by gkushang** [comment]
yes, this html-reporter has no limitations on screenshots. As you write your tests, you can attach screenshots at any steps. Let us know if you need any help with attaching the screenshots to the report

**Comment by gnaneswarreddy** [comment]
I can only get the screenshots for the failed step at the end of the scenario where to add the code for enabling it in every step? I am using nightwatch api and cucumber-html-reporter

**Comment by gnaneswarreddy** [comment]
Hi, Please let me know how we can get the screenshots for all the steps and to be attached in the report?

**Comment by gnaneswarreddy** [comment]
Any update?

**Comment by gnaneswarreddy** [comment]
I am using nightwatch api any help is appreciated please?
