### ISSUE TITLE
How To Include Version Information Of Application Under Test In Report

### ISSUE THREAD

**Issue by bhreinb** [gkushang/cucumber-html-reporter#18]
Hi There,

I have a number of test scenarios that are run on a feature. This gets wrote to the JSON file which I convert to HTML as expected. All good so far.

However, I would like to include version info of the AUT (Application Under Test) included in the HTML report. Is there a JSON property which one can write AUT test details (i.e. for example browser versions, angular version, software under test versions, etc) so that this module can parse and display this within the final generated report.

It would be a very nice feature to have if it isn't already there. Thanks in advance.

**Comment by thyagab** [comment]
@bhreinb are you talking about something like protractor capabilities to be added to report?

**Comment by bhreinb** [comment]
Something along that lines..in addition for example I execute a JavaScript query on the browser that gets the angular version, frontend AUT & Back end AUT...ideally I'd like that information to be displayed in the report. Hope that makes sense?

**Comment by bhreinb** [comment]
Hello @thyagab @gkushang @li-qiang. Would it be possible to get version info added to a report as per my request above. Btw the reports returned from the module are great :+1:

**Comment by gkushang** [comment]
Hi @bhreinb - Thanks. We are happy to hear that. How do you want to to print the info on report? The reporter will print the info if they are attach to scenario - `scenario.attach('my info...')`. We print our info on `Before` hook. Would it help?

**Comment by bhreinb** [comment]
Hi @gkushang  I'm probably verging into new feature request territory but here goes.

I was thinking for instance at the top of the report you would have a table just above the pie charts in the case of "bootstrap" report that could be filled with version info. See sample below

![versioninfo](https://cloud.githubusercontent.com/assets/20628685/18783326/12277690-8183-11e6-8472-528e34f90a0d.png)

Basically the cucumber JSON would have a new field namely versioninfo or something more appropriately named

`"versioninfo":
{
	"Configuration": "Version",
	"Platform": "win32",
	"Browser": "52.0.2743.116",
	"Angular Edition": "1.5.7",
	"UI": "1.2.80",
	"API": "1.2.0.33",
	"Test Environment": "DEV_EXTERNAL"
}`

(Of course it would be an expectation that the cucumber JSON would be modified before passing onto this module...if field "versioninfo" isn't there then do nothing)

So the module would interpret that new field and display in the report as per normal depending on how many key/values pairs are passed in "versioninfo" field


In any case thanks for suggesting the above workaround. I have appended this version info in the before hooks for each scenario but I don't favor polluting each scenario with version info related details. Thanks for your help.

**Comment by bhreinb** [comment]
Hello @gkushang any idea when we may get this feature request added to the module?

(Many thanks in advance)

**Comment by gkushang** [comment]
@bhreinb As you mentioned, Cucumber won't generate the JSON with `versionInfo` filed so it's more likely customizing JSON report before passing to report - so lets go with generic object naming, e.g. `additionalInfo` and will add it to the report.

**Comment by bhreinb** [comment]
@gkushang Yeah I wouldn't expect Cucumber to generate `versionInfo` as JSON so I would fully expect to modify the JSON before passing to the report....happy to go with any naming convention that suits...thx a mill :+1:

**Comment by gkushang** [comment]
https://github.com/gkushang/cucumber-html-reporter/pull/39 adds this feature.

**Comment by bhreinb** [comment]
Hey @gkushang this commit you added looks great...would you be able to make it available to us in the next day or so for usage etc....appreciate you adding this feature

**Comment by gkushang** [comment]
published with v@0.3.2
