### ISSUE TITLE
Steps marked as hidden should not be visible in the report

### ISSUE THREAD

**Issue by AlexandrosD** [gkushang/cucumber-html-reporter#19]
Virtual steps, like `Before` or `After` hooks, are marked as hidden, i.e. they have the property `hidden: true` in cucumber's json report.

These steps should not be counted or shown in the report.
An exception is when these steps contain attachments (e.g. screenshots), something that is quite common in `After` hooks

**Comment by gkushang** [comment]
@AlexandrosD Thanks for contributing - released as a part of `v0.2.10`
