### ISSUE TITLE
Support cucumber-js v6

### ISSUE THREAD

**Issue by NathanAB** [gkushang/cucumber-html-reporter#202]
There are breaking changes to the JSON output in the v6 release of cucumber-js, please see here: https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#breaking-changes

**Comment by macasas** [comment]
I'm using 
cucumber-js 6.0.2
cucumber-html-reporter 5.0.2

but when I try to generate the report I get 

```
> node html-report.js

/Users/Projects/server_repo/node_modules/cucumber-html-reporter/lib/hierarchyReporter.js:21
    suite.features.forEach(function (feature) {
                   ^

TypeError: suite.features.forEach is not a function
    at Object.getBaseDir (/Users/Projects/server_repo/node_modules/cucumber-html-reporter/lib/hierarchyReporter.js:21:20)
    at setStats (/Users/Projects/server_repo/node_modules/cucumber-html-reporter/lib/reporter.js:201:41)
    at generateReport (/Users/Projects/server_repo/node_modules/cucumber-html-reporter/lib/reporter.js:431:13)
    at Object.generate (/Users/Projects/server_repo/node_modules/cucumber-html-reporter/lib/reporter.js:483:9)
    at Object.generateReport [as generate] (/Users/Projects/server_repo/node_modules/cucumber-html-reporter/index.js:30:21)
    at Object.<anonymous> (/Users/Projects/server_repo/html-report.js:17:14)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

Is this the same issue, same breaking change?
Is there a workaround, or should I wait for an update?

**Comment by iAbhishek91** [comment]
Facing same problem. It seems recently V6.* of cucumber changed the JSON format drastically. Please upgrade the report module.

**As a workaround, I have downgraded cucumber to V5.1.0.**

**Comment by macasas** [comment]
Thanks.

Googled downgrading and instructions say to use `npm install cucumber@5.1.0 --save-dev` to downgrade. This didn't work, with `./node_modules/.bin/cucumber-js --version` still returning 6.0.2 so I deleted the node_modules folder and ran `npm install`

I'm now running fine, with html reporting, so thanks.

**Comment by jonbeller** [comment]
I started looking into the changes cucumber-html-reporter would need to implement. 

The best way I've found to view how the cucumber-js JSON formatter structure has changed was to look at diff for json_formatter_spec.js [in the PR that implemented retries](https://github.com/cucumber/cucumber-js/pull/1205/files#diff-be9a2ba0d5e05ec32bf9f46ee4dd19d4L28).

It's not obvious to me how to use the new format.

**Comment by gkushang** [comment]
Hello Everyone, thank you all for the feedback. 

Looking at Cucumber.JS documentations, it seems like the JSON Formatter support is Restore back in `v6.0.3` same as V5.

Cucumber Issue: https://github.com/cucumber/cucumber-js/issues/1244

```
I understand us supporting the old JSON formatter but am curious if its worth building a new one at some point

Done in release 6.0.3.```
--


@NathanAB or anyone in this thread. 

Can you please verify and confirm if `cucumber-html-reporter@5.1.0` version works fine with `cucumber@6.0.3` or above version?

If not, we will prioritize this support in the reporter. 

Thank you!

**Comment by Shinigami92** [comment]
I will test it tomorrow

**Comment by Shinigami92** [comment]
YAY \o/
It is working 🎉

**Comment by gkushang** [comment]
Wow, great 💯

Thanks for quickly testing @Shinigami92 👍Closing this issue now!
