### ISSUE TITLE
Not support in cucumber version 6 or later.

### ISSUE THREAD

**Issue by subhamishra** [gkushang/cucumber-html-reporter#208]
In cucumber version 6 or later they changed there result file(JSON file) format. while parsing the JSON file inside the reporter.js it is throwing error.

**Comment by gkushang** [comment]
@subhamishra 

Looking at Cucumber.JS documentations, it seems like the JSON Formatter support is Restore back in v6.0.3 same as V5.

Cucumber Issue: cucumber/cucumber-js#1244
```
I understand us supporting the old JSON formatter but am curious if its worth building a new one at some point

Done in release 6.0.3
```

Can you please verify and confirm if cucumber-html-reporter@5.1.0 version works fine with cucumber@6.0.3 or above version?

If not, we will prioritize this support in the reporter.

Thank you!

**Comment by gkushang** [comment]
@subhamishra it was verified with https://github.com/gkushang/cucumber-html-reporter/issues/202, it works in later Cucumber 6th versions, so closing this issue now.
