### ISSUE TITLE
How to include time information

### ISSUE THREAD

**Issue by jontxo** [gkushang/cucumber-html-reporter#24]
Hello

First of all thank you very much for your work.
I am using the report tool in a python project with pytest-bdd and I would like to know if it would be possible to make the tool include information about how long it takes to complete each step, scenario or feature.

Regards

**Comment by gkushang** [comment]
Hi @jontxo - PR https://github.com/gkushang/cucumber-html-reporter/pull/17 by @Galileo1 will include these information at step level

**Comment by jontxo** [comment]
Hello

Thank you for the info. That was what I was looking for.

Regards
