### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by larryg01** [gkushang/cucumber-html-reporter#269]
Hi @gkushang 

We have upgraded the project on github and would like to get permission to publish it to NPM
Can this be arrange please of can you pull the code and do the publish

**Comment by gkushang** [comment]
@larryg01  - apologies for the delay. Published the version v5.5.1

**Comment by larryg01** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.EmailStyle19
	{mso-style-type:personal-reply;
	font-family:"Calibri",sans-serif;
	color:windowtext;}
MsoChpDefault
	{mso-style-type:export-only;
	font-size:10.0pt;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
***@***.*** I have to admit this should have been published as v6 because it was a major upgrade doing it as v5.5.1 suggest that it was just a minor change. Hence the reason I made a v6 build in github.  Thanks and RegardsLarryG https://btaawards.com/2023-finalists/#developer Larry Goddard | Test Automation ***@***.*** T: https://twitter.com/LarryG_01L: https://linkedin.com/in/larryg/Y: ***@***.***_01  From: Kushang Gajjar ***@***.***>Date: Monday, 13 March 2023 at 23:58To: gkushang/cucumber-html-reporter ***@***.***>Cc: LarryG ***@***.***>, Mention ***@***.***>Subject: Re: [gkushang/cucumber-html-reporter] Publish to NPM (Issue ***@***.*** - apologies for the delay. Published the version v5.5.1—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by larryg01** [comment]
It has been published now  Thanks and RegardsLarryG https://btaawards.com/2023-finalists/#developer Larry Goddard | Test Automation ***@***.*** T: https://twitter.com/LarryG_01L: https://linkedincom/in/larryg/Y: ***@***.***_01  From: Tony Tu ***@***.***>Date: Tuesday, 14 March 2023 at 13:31To: gkushang/cucumber-html-reporter ***@***.***>Cc: LarryG ***@***.***>, Mention ***@***.***>Subject: Re: [gkushang/cucumber-html-reporter] Publish to NPM (Issue #269)Just follow up. When will this new release be published to NPM?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
