### ISSUE TITLE
package.json not found

### ISSUE THREAD

**Issue by mucsi96** [gkushang/cucumber-html-reporter#29]
When I generate html report from a subdirectory as `cwd` I got an error message `Error: ENOENT: no such file or directory, open 'c:\Users\mucsi\repos\nightwatch-cucumber\examples\multi-example\packa
ge.json'`. Is it possible to provide the name and version using configuration object instead of reading `package.json` of the current directory?

**Comment by gkushang** [comment]
yes, you can provide `name` thru the configuration options as described [here](https://github.com/gkushang/cucumber-html-reporter#name). However, `version` is not customized yet but will customize it.
