### ISSUE TITLE
Not working in older node js version (anymore)

### ISSUE THREAD

**Issue by SirLenz0rlot** [gkushang/cucumber-html-reporter#30]
0.2.11 worked fine, 0.2.14 not.
I guess this is because of the older NodeJS version I'm working with.

It says: Fatal error: Object #<Object> has no method 'trunc'

I'm guessing this is related to `Math.trunc` being used in reporter.js, which is a relatively recently added method.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc

**Comment by gkushang** [comment]
thanks for reporting with details @SirLenz0rlot. This is fixed with https://github.com/gkushang/cucumber-html-reporter/pull/31. We will publish soon

**Comment by gkushang** [comment]
published with 0.2.15. Please reopen the issue if you are still facing.

**Comment by SirLenz0rlot** [comment]
Thanks for the very fast response, I just verified the latest version again.
