### ISSUE TITLE
The CucumberJs Framework Supports Description At Scenario Level Could this Be Added To Html Report

### ISSUE THREAD

**Issue by bhreinb** [gkushang/cucumber-html-reporter#33]
Hi There,

The cucumber js framework now support "description" at Feature & Scenario level as of version cucumber@1.3.1. This module currently displays description property at Feature Level i.e. it displays it in the HTML report, however doesn't support description at scenario level.

Could this be added please? Many thanks in advance.

Ticket to get it added to cucumberjs framework can be found here @ 

https://github.com/cucumber/cucumber-js/issues/647

which was committed over the weekend.

**Comment by gkushang** [comment]
@bhreinb that sounds good. We will add in our next release. Thanks!

**Comment by gkushang** [comment]
Support added to `v0.2.16`
