### ISSUE TITLE
Adding support to ambiguous steps 

### ISSUE THREAD

**Issue by Galileo1** [gkushang/cucumber-html-reporter#36]
Hey,

You might have noticed the cucumber version > 0.7.0 have new "ambiguous" status for steps.Can we add support for ambiguous please.Currently it's been picked up as undefined.

Thanks

**Comment by jlin412** [comment]
+1

**Comment by Galileo1** [comment]
I have started working  on this will submit the PR soon

**Comment by Galileo1** [comment]
@gkushang @jlin412 Guys, 

I have done some changes to the support the "ambiguous" status for gherkin steps. To know about ambiguous status see [here](https://github.com/cucumber/cucumber/wiki/Step-Definitions#ambiguous-steps).

Below are some of the changes that I have done .Happy to discuss about these changes (still in my branch).

The index will look like this. I have a second though about the Feature pie chart - that we should relay all the ambiguous as failed and just have failed/passed status where as the scenario pie chart shows that detailed report. The reason I am thinking like this is because on cmdline, ambiguous is represented as failed(x red color). 

![image](https://cloud.githubusercontent.com/assets/9716232/20467358/d7b0561c-afea-11e6-900c-ffb5353ae021.png)

![image](https://cloud.githubusercontent.com/assets/9716232/20467393/a706d44a-afeb-11e6-9fba-7e601bc4baad.png)

The feature and scenario reporting will look like this -
Feature as usual will report that the scenario/(s) passed or failed or is ambiguous(represented as ? ).
Scenario will report the status of steps and report accordingly.

Please let me know if this looks fine.

![image](https://cloud.githubusercontent.com/assets/9716232/20467421/2ffbbebe-afec-11e6-940f-34db58dd2dff.png)

**Comment by Galileo1** [comment]
Similar kind of change has been made to foundation.tmpl
![image](https://cloud.githubusercontent.com/assets/9716232/20468722/642374f4-affe-11e6-9efa-d8daf971b9e4.png)

**Comment by gkushang** [comment]
@Galileo1 this looks nice! Feel free to submit a PR

>> I have a second thought about the Feature pie chart - that we should relay all the ambiguous as failed and just have failed/passed status where as the scenario pie chart shows that detailed report.

Does that mean any ambiguous step should show as FAILURE on feature pie-chart, but should show as ambiguous on Scenario chart?

**Comment by Galileo1** [comment]
@gkushang Yeah that's what I was thinking of but then report will look inconsistent.So I think we drop it??

**Comment by gkushang** [comment]
Yes, you are right. We only maintain Pass/Fail at feature level, so if none of the scenarios failed then it should be 100% pass at feature chart

**Comment by gkushang** [comment]
published with v0.3.3
