### ISSUE TITLE
Webdriver errors in cucumber report 

### ISSUE THREAD

**Issue by Galileo1** [gkushang/cucumber-html-reporter#41]
@gkushang  Just a thought. It did be cool if we can pull out the errors from webdriver in  cucumber report. 
 Is it  possible??

**Comment by gkushang** [comment]
Generally, it's up to users to push error messages to the Reporter whether it's selenium test or API tests. User can attach any type of message to scenario, even user can add HTML styles to error message or info, as per [these](https://github.com/gkushang/cucumber-html-reporter/blob/develop/README.md#tips) readMe examples.

Is that what you've suggested?

**Comment by Galileo1** [comment]
Hey, 

What I meant was error like "No such element found" which is thrown by Webdriver on the console. I have checked the webdriver library and there is no method that's been exposed to capture these errors. 

example - I can grab the errors thrown by AUT on the browser console using -browser.manage().logs().get('browser').But is there a method that would allow me to capture the errors that driver throws (snapshot attached)? Something like browser.manage().logs().get('console'). I think (assumption) this is possible in firefox and that two it's not straight forward. 

![image](https://cloud.githubusercontent.com/assets/9716232/20638035/e8fdfe34-b3fe-11e6-83ef-5d8aba899ee0.png)

What do you think?

**Comment by Galileo1** [comment]
some more - 
http://jimevansmusic.blogspot.co.nz/2013/09/capturing-javascript-errors-in.html
https://www.3pillarglobal.com/insights/how-to-capture-javascript-errors-from-your-web-application
https://github.com/mguillem/JSErrorCollector

**Comment by gkushang** [comment]
IMO - we should keep the Reporter independent of any webDriver/API related operations. Still, user can attach/pretty the Errors on report thru `scenario.attach`. @After hook will be the best place to capture and attach error to report.

**Comment by Galileo1** [comment]
@gkushang I agree that reporter should be independent of any webDriver/API but the question was more towards "how to" capture those driver errors. And for where? - then yes we can attach that to the report in After hook. But that's fine, really appreciate for listening and replying back. I will close this issue.
