### ISSUE TITLE
skipping blank json files during parallel running

### ISSUE THREAD

**Issue by Galileo1** [gkushang/cucumber-html-reporter#49]
Hey @gkushang,

Can we please skip the Json files which are blank and gets created during parallel running?
they are blank because cucumber tries to run tagged(~@ignore) case but doesn't. And end up producing empty output json files.

What do you think?I can create a PR for that if you r fine.

**Comment by gkushang** [comment]
Sure, please go ahead and submit a PR. I am swamped these days 😄

**Comment by gkushang** [comment]
@Galileo1 do you have any update on this issue?

**Comment by gkushang** [comment]
@Galileo1 

I believe the ask has been added to the module. Please confirm or reopen the issue since it has been quite inactive for while.

Thanks!

**Comment by Galileo1** [comment]
sure @gkushang I will check it out..
