### ISSUE TITLE
Integration with protractor-cucumber

### ISSUE THREAD

**Issue by Sharique-Hasan** [gkushang/cucumber-html-reporter#54]
I could not find a way to integrate it with my protractor config, the way I integrated cucumber. I only found cucumberjs command line to generate the json which in turn generated undefined reports.
![screencapture-file-e-sharique-development-developmentdata-projects-bb_bulldozair_webclient_v2-e2e-ts-report-cucumber_report_bootstrap-html-1489959434508](https://cloud.githubusercontent.com/assets/2499521/24085023/4e03765e-0d16-11e7-9139-219ea258cd80.png)

I am using following cucumberOpts with protractor:

```
cucumberOpts: {
        compiler: "ts:ts-node/register",
        strict: true,
        format: ['pretty'],
        require: ['../../stepdefinitions/**/*.ts', '../../support/*.ts'],
        tags: '@ProtractorScenario'
    }
```

**Comment by Sharique-Hasan** [comment]
@gkushang Am I missing something in config snippet?

**Comment by gkushang** [comment]
@Sharique-Hasan I don't have insights on Protractor framework but looking at the config, can you try to set the `format: json` and pass the JSON file to the reporter?

**Comment by gkushang** [comment]
@Sharique-Hasan 

I hope you have un-covered the Protractor integration. I am going to close this issue since it's not related to this module. But I will be happy if you could share the solution you found to help others.

Please give feedback if something comes up.

Thanks!
