### ISSUE TITLE
Cucumber doesn't do - Base64 encoding for text attachments with mime-type 'text/plain'

### ISSUE THREAD

**Issue by rjayagopal** [gkushang/cucumber-html-reporter#55]
Cucumber doesn't do - Base64 encoding for text attachments with mime-type 'text/plain'

if (embedding.mime_type === 'text/plain') {
                                if (!step.text) {
                                    step.text = Base64.decode(embedding.data);
                                } else {
                                    step.text = step.text.concat('<br>' + Base64.decode(embedding.data));
                                }
                            }

Could you please remove the Base64.decoding - this is making the attached texts to "JUNK VALUES"

**Comment by gkushang** [comment]
Could you share some examples of the text data and how do you try to attach to the report?

**Comment by rjayagopal** [comment]
Hi,

Am just doing it in straight forward way.

this.attach('sample text');

In the step definition methods.

Regards,
Raghul J
+61 469057650



On 20/03/2017 1:37 pm, "Kushang Gajjar" <notifications@github.com> wrote:

Could you share some examples of the text data and how do you try to attach
to the report?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gkushang/cucumber-html-reporter/issues/55#issuecomment-287668912>,
or mute the thread

**Comment by gkushang** [comment]
It should print OK. I ran the `npm test` on module without `clean` and it prints the string okay as per below screenshot,

The code to print is [here](https://github.com/gkushang/cucumber-html-reporter/blob/develop/test/features/step_definitions/stepDefs.js#L50-L55),

```
        var myJsonObject = {
            name: 'cucumber-html-reporter',
            format: 'html'
        };

        this.scenario.attach(JSON.stringify(myJsonObject, undefined, 2));

```


**HTML Report:**

<img width="1001" alt="screen shot 2017-03-20 at 1 11 24 pm" src="https://cloud.githubusercontent.com/assets/3663389/24112131/e6b7dc8e-0d6e-11e7-9208-63fb8ee3ed74.png">

Let us know if you still face the issue or paste the HTML report screenshot to help debug further

**Comment by rjayagopal** [comment]
Hi Kush,

Thanks a lot for your support.

I am still facing the same issue and noticed you are using cucumber 1.3.1,
am on cucumber version 2.0.0-rc.9 and there were enhancements to the
Attachments API post 1.x versions.

Cheers,

Raghul Jayagopal

Cell: (+61) 469-057-650

**Comment by rjayagopal** [comment]
Cucumber ChangeLOG:

2.0.0-rc.0 (2016-11-25)
    JSON Formatter
        **String attachments are no longer base64 encoded.** Buffer and Stream attachments are still base64 encoded.

**Comment by gkushang** [comment]
Hi @rjayagopal, the Cucumber v2 is still in the Beta phase. Let's revisit/update any changes when cucumber2 releases.

**Comment by stevehipwell** [comment]
@gkushang cucumber-js c2 is now at rc.

@rjayagopal the workaround is as follows:
`return this.attach(Buffer.from('Hello world!').toString('base64'));`

**Comment by gkushang** [comment]
@stevehipwell thanks for stepping in. I will take a look at upgrading the reporter.

**Comment by gkushang** [comment]
https://github.com/gkushang/cucumber-html-reporter/pull/81 will fix this issue

**Comment by gkushang** [comment]
published the fix with `cucumber-html-reporter@2.0`. Please try it out, and let us know how it works.

**Comment by rjayagopal** [comment]
Hi,

I just did in straight forward way.

this.attach('sample text');

In the step definition methods.


On 20/03/2017 1:37 pm, "Kushang Gajjar" <notifications@github.com> wrote:

Could you share some examples of the text data and how do you try to attach
to the report?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gkushang/cucumber-html-reporter/issues/55#issuecomment-287668912>,
or mute the thread

**Comment by gkushang** [comment]
@rjayagopal

Did it work with latest reporter version?

**Comment by nanichandu84** [comment]
I am importing, import { defineSupportCode,Scenario } from 'cucumber';

Updated reporter version to 2.0.2 and, if I just do, this.attach(new Buffer(jsonData, 'base64'), 'application/json'), in my step definition, 
I am getting "Cannot read property 'attach' of undefined" error.

If I do, this.scenario.attach(new Buffer(jsonData, 'base64'), 'application/json'), then I am getting " TypeError: Cannot read property 'scenario' of undefined"

Do I need to add anything in hooks file?
