### ISSUE TITLE
0.3.8 - Issue when generating the report

### ISSUE THREAD

**Issue by JmacedoV** [gkushang/cucumber-html-reporter#58]
Hi,

So I just updated to the latest version of the report, noticed that some changes were made, didn't see nothing on the changelog that would need reconfiguration on my side.

When running the report I get the following error 

`const assign = require('./util/assign')
^^^^^
SyntaxError: Use of const in strict mode.`

My config file: 

```javascript
var reporter = require('cucumber-html-reporter');
var options = {
        theme: 'bootstrap',
        jsonFile: 'cucumber_report.json',
        output: 'cucumber_report.html',
        reportSuiteAsScenarios: false,
        launchReport: true,
        component: "Test"
    };

    reporter.generate(options);
```

Posting here since it seems that it might be a bug

Thanks in advance

**Comment by gkushang** [comment]
@JmacedoV thanks for reporting the issue. What are your node and npm versions?

**Comment by JmacedoV** [comment]
Hi @gkushang 

node - v0.10.25
npm - 1.3.10

Cheers

**Comment by gkushang** [comment]
I see the issue isn't reproducible for node version >0.12. We will revert the commit for backward compatibility and publish a MAJOR version for latest stable node versions.

**Comment by gkushang** [comment]
Fixed. Added a support for backward compatibility - checkout the [changelog](https://github.com/gkushang/cucumber-html-reporter/blob/develop/CHANGELOG.md#039-2017-03-24) for the specific version

**Comment by JmacedoV** [comment]
Thanks for all the help !
