### ISSUE TITLE
Reporter generating extra step "After" even though it doesn't exist !

### ISSUE THREAD

**Issue by igniteram** [gkushang/cucumber-html-reporter#6]
This is rather strange issue, I am getting an extra step **"After"** in the html report. It exists no where in my feature files 
**cucumber_html report**
<img width="1552" alt="screen shot 2016-06-29 at 5 38 28 pm" src="https://cloud.githubusercontent.com/assets/15998104/16451608/b3ee2136-3e21-11e6-89c8-315ad737d2b6.png">

**My Feature File**
<img width="450" alt="screen shot 2016-06-29 at 5 38 57 pm" src="https://cloud.githubusercontent.com/assets/15998104/16451632/dc445498-3e21-11e6-9afa-51edf1062ca2.png">

**The html code**
<img width="757" alt="screen shot 2016-06-29 at 5 39 42 pm" src="https://cloud.githubusercontent.com/assets/15998104/16451644/eaeaa7a4-3e21-11e6-80d9-7b6211c8f12f.png">

**Comment by gkushang** [comment]
Hi @igniteram, can you check for the ` "keyword": "After "` in your JSON file? If you find then you can further check for the ` "location":` in the After object to see where it is coming from?

e.g. JSON,

```
          {
            "arguments": [],
            "keyword": "After ",
            "result": {
              "status": "passed",
              "duration": 98607
            },
            "hidden": true,
            "match": {
              "location": "path/to/after-hook:line-number"
            }
          }
```

**Comment by igniteram** [comment]
@gkushang thats coming from my **hooks.js** file, but that is an hook for scenarios to take screenshots

![screen shot 2016-06-29 at 9 03 38 pm](https://cloud.githubusercontent.com/assets/15998104/16458548/0e09b4a8-3e3d-11e6-90c8-0a3027fccef6.png)

**Comment by gkushang** [comment]
Glad you found out. Since it's part of Scenario execution, it will be on HTML report as well. In your case, if scenario fails then HTML report will also attach PNG file captured in the `After` hook.

**Comment by igniteram** [comment]
hi, but in the JSON file the hooks are set to `hidden= true` so the reporter should exclude these while creating, as you can see rest of the scenarios do not have `hidden` key 

```
   {
            "arguments": [],
            "keyword": "Then ",
            "name": "I clear search textbox",
            "result": {
              "status": "passed",
              "duration": 295992
            },
            "line": 8,
            "match": {
              "location": "mylocation"
            }
          },
          {
            "arguments": [],
            "keyword": "After ",
            "result": {
              "status": "passed",
              "duration": 202033
            },
            "hidden": true,
            "match": {
              "location": "/mylocation"
            }
          }
```

**Comment by gkushang** [comment]
@igniteram that is true. I'm not sure what does it expected to do there. I've asked at Cucumber form. However, if you hide the `After` hooks then you will loose the data on HTML reports. Data could be anything including any Failure Error stackTrace, Screenshots attachments etc. After hook closes the tests and any uncaught error will be reported there, so I'd recommend not to hide the hook but report as much as information.

**Comment by gkushang** [comment]
@igniteram I hope this issue is resolved. Please reopen if required.
