### ISSUE TITLE
Step duration time in html report always shows 0s

### ISSUE THREAD

**Issue by sampreethnd** [gkushang/cucumber-html-reporter#61]
I'm using cucumber-html-reporter with nightwatch-cumber. The cucumber_report.json file generated after running the tests has step duration in milliseconds. For calculating the step duration, it looks like cucumber-html-reporter always expects the step duration to be in nanoseconds, due to this the step duration in the html report is always shown as 0s. Could this issue be looked into please?

**Comment by stevehipwell** [comment]
We're seeing the same issue here.

cucumber-js: 2.0.0-rc.9

**Comment by gkushang** [comment]
I believe https://github.com/gkushang/cucumber-html-reporter/pull/62 would solve the issue. Could you please verify, or paste the sample JSON for us to verify?

**Comment by sampreethnd** [comment]
@gkushang I verified with #62, it does solve the issue. When will this change be released?

**Comment by gkushang** [comment]
@sampreethnd thanks for verifying. The PR is still open. I expect to publish in next two days - will update here!

**Comment by sampreethnd** [comment]
@gkushang thanks a lot. That would be great.

**Comment by gkushang** [comment]
the fix is published with v0.4.1

**Comment by stevehipwell** [comment]
@gkushang I'm now seeing no duration rather than *0s*.

**Comment by gkushang** [comment]
@stevehipwell good catch! Fixed with v0.4.2

**Comment by stevehipwell** [comment]
@gkushang it looks like it's back to reporting *0s*.

**Comment by gkushang** [comment]
It will report 0 if in nanosecond. Can you share your json sample or a step duration?

**Comment by stevehipwell** [comment]
@gkushang I've attached a sample report with two scenarios.

[cucumber.zip](https://github.com/gkushang/cucumber-html-reporter/files/964267/cucumber.zip)

**Comment by gkushang** [comment]
thanks @stevehipwell. There are lot of changes in Cucumber V2 after digging through the change log, e.g. the duration is changed to milliseconds from nano and also the attachment API changed as well. To support Cucumber V2, we will be releasing the major version and will keep the current version as a backward compatible. Re-opening the issue as it's not completely resolved yet.

**Comment by gkushang** [comment]
https://github.com/gkushang/cucumber-html-reporter/pull/81 will fix this issue

**Comment by gkushang** [comment]
published the fix with `cucumber-html-reporter@2.0`. Please try it out, and let us know how it works.
