### ISSUE TITLE
Counting After Hooks as  Steps

### ISSUE THREAD

**Issue by joanaaraujo88** [gkushang/cucumber-html-reporter#63]
Even hidden, after hooks are being counted in counters as steps on the report. 
On the image we can see only 5 steps but the counter shows 7.

![screen shot 2017-04-18 at 15 30 53](https://cloud.githubusercontent.com/assets/18311213/25138913/b0d735d2-2453-11e7-9e7b-5fd6d18f8647.png)

**Comment by gkushang** [comment]
@joanaaraujo88 Please take a look at https://github.com/gkushang/cucumber-html-reporter/pull/64. It fixes the issue.
