### ISSUE TITLE
Why execution time is displaying as 0s for all the steps in the report

### ISSUE THREAD

**Issue by nanichandu84** [gkushang/cucumber-html-reporter#65]
![image](https://cloud.githubusercontent.com/assets/26753645/25590788/ae01fd34-2e66-11e7-97c4-65d6912dc88c.png)

**Comment by nanichandu84** [comment]
![image](https://cloud.githubusercontent.com/assets/26753645/25590742/9b970306-2e66-11e7-899b-af8773a978a3.png)

**Comment by gkushang** [comment]
thanks @nanichandu84 for reporting the issue. Please follow the https://github.com/gkushang/cucumber-html-reporter/issues/61 for updates.

**Comment by gkushang** [comment]
https://github.com/gkushang/cucumber-html-reporter/pull/81 will fix this issue

**Comment by gkushang** [comment]
published the fix with `cucumber-html-reporter@2.0`. Please try it out, and let us know how it works.
