### ISSUE TITLE
When used as a dependency Error: no such file or directory, open 'C:\stage\package.json'

### ISSUE THREAD

**Issue by dubbya** [gkushang/cucumber-html-reporter#66]
Im using as a dependency in my app and it looks for a package.json in my local folder (but my app is global). I will submit a PR, just needs some default name and version in reporter.js

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode)
Error: ENOENT: no such file or directory, open 'C:\stage\package.json'

**Comment by gkushang** [comment]
@dubbya 

I am closing this issue since you've committed a fix. 

Thanks!
