### ISSUE TITLE
Wrap text earlier to keep Scenario title visible

### ISSUE THREAD

**Issue by andrialexandrou** [gkushang/cucumber-html-reporter#69]
![screen shot 2017-05-05 at 2 14 19 pm](https://cloud.githubusercontent.com/assets/14981214/25760643/51a4acfa-319d-11e7-804f-873fb347b861.png)

^ Just a teensy request. I've been extracting the text from the DOM via dev tools, but for other folks at the company having all that title visible would be supes helpful.

Thanks, friends! If I have a moment myself here in the next few weeks I may commit some dev time to it myself. Til then, wanted to open it should it be an easy fix for you folks or someone else.

**Comment by gkushang** [comment]
fixe as a part of https://github.com/gkushang/cucumber-html-reporter/pull/78
