### ISSUE TITLE
[PROPOSE] New report template 'hierarchy' based on bootstrap but adding folder hierarchy

### ISSUE THREAD

**Issue by cstrong** [gkushang/cucumber-html-reporter#75]
Hey maintainers, thanks for an awesome tool!

**Problem Statement**
I love the bootstrap format, but I think it may start to look cluttered once I add more than 100 features.

**Proposed Solution**
What about the concept of creating a new template that looks like the bootstrap template except that the features are contained within a hierarchy that corresponds with the folder structure that the features are in?
`authentication/`
`authentication/login/`
`authentication/logout/`
`shoppingcart/`
`shoppingcart/discounts/`
`shoppingcart/salestax/`
The folder structure could use the same type of expand/collapse panel that the features/scenarios do.
That way we get a report that brings in some of the goodness of "living documentation" tools such as https://relishapp.com/explore or http://www.picklesdoc.com/    
I believe this format could also be easier for management to read -- they could get a quick overview and then drill down for insights into which areas of the code have problems, or which areas are less or more well-tested.

**Implementation Details**
So.. I forked the repo and I am looking at creating a recursive set of suite objects.   The template would create a suite container recursively until it found a suite with only features inside and no embedded suite object, then it would go with the standard feature template logic.
I believe I can do this in a backward compatible way so that all of the existing report templates will still work fine.   

**Summary**
So this is just to see if there is interest out there, and to get comments from the maintainers.
I plan to finish this work by end of May 2017 and submit a pull request for review.
Please let me know if there is anything special I should do.   Thanks very much!

**Comment by gkushang** [comment]
Hi @cstrong - Thank you for taking time to explain the proposal nicely. I love the idea. What happens if there is only directory, `features/.*feature`? I believe, that would default to the current existing structure and would render any `directory` under `features` directory (if nested) as a separate tabs on HTML? Right?

e.g. 
features
  |
  |----x.feature
  |----y.feature
  |----authentication
                    |
                    |----login.feature
                    |----logout.feature
 |----shoppingcart
                    |
                    |----discounts.feature
                    |----salestax.feature


Would render as 5 TABS on HTML? x.feature, y.feature, authentication, shoppingcart?

**Comment by cstrong** [comment]
Yes, x and y would appear under the top level "All Features" container, then login and logout appear under "authentication" and discounts and sales tax appear under "shopping cart".
Right now the report renders sub-folders above nested features, so authentication and shopping cart would appear before x and y in "All Features."   That could be inverted though.
I just finished, should be posting the code shortly.

**Comment by cstrong** [comment]
BTW I could not figure out how to support arbitrary levels of sub-suite nesting.  It is currently hardcoded to support up to 3 nested levels.   If you can figure out how to do this, please let me know.   
I think there are some limitations as long as we stick with lodash template strings, rather than a more powerful framework like React.   As a point of interest, another test reporting project recently went through exactly this kind of transformation: https://github.com/lukejpreston/junit_viewer (mustache templates) became https://github.com/lukejpreston/xunit-viewer (React).
I realize that is a big step, and would be lots of work.  Probably we can squeeze some more mileage out of the current approach at least for awhile.

**Comment by cstrong** [comment]
Thanks for merging in the PR!  Closing issue now.   Please make a new release when you get a chance

**Comment by gkushang** [comment]
@cstrong published v5.0.0. thanks!
