### ISSUE TITLE
Screenshot embedding

### ISSUE THREAD

**Issue by pawankums** [gkushang/cucumber-html-reporter#80]
hi, i am using espresso, cucumber and spoon for android testing. I am converting the json file to the html report using given javascript function. But i am unable to understand that how to embed the screenshot in the html report.
Using espresso we can take screenshot as Spoon.screenshot(Activity, "tag"). but there is not method as then as shown in your example. Please guide me through this.

Thanks

**Comment by gkushang** [comment]
@pawankums  What is your Cucumber version?

**Comment by pawankums** [comment]
@gkushang it is 1.2.5

**Comment by gkushang** [comment]
Can you take a look at https://github.com/sebaslogen/espresso-cucumber/issues/1? It might help you.

**Comment by pawankums** [comment]
Thanks @gkushang  i will have a look at it.

**Comment by gkushang** [comment]
@pawankums 

Hope it helps! Feel free to provide any further feedback and re-open the issue. 

Thanks!
