### ISSUE TITLE
Supporting multicapabilities with consolidated cucumber JSON for protractor

### ISSUE THREAD

**Issue by thyagab** [gkushang/cucumber-html-reporter#9]
Is there a way that we can generate a consolidated report when we run tests in parallel with protractor?
Can we have set of JSON files(more than one json file as input) as input and the reporter can generate a consolidated report?

**Comment by gkushang** [comment]
@thyagab it is not supported yet. It can be done outside of the module. I just did a random search and found  [jsonmerge](https://github.com/Jayin/jsonmerge) can do that. Please take a look at it. 

It'd be good have a support of multiple JSON's. Feel free to submit a PR to the module once you have the consolidated JSON.

HTH!

**Comment by thyagab** [comment]
@gkushang If I can generate the consolidated file then I can use the existing module itself to generate the report. No need of PR.

**Comment by thyagab** [comment]
@gkushang tried using the jsonmege, but it is not properly merging and generates a output
{
    "0": {
        "description": "  As a user, I should be able to login with valid credentials",
        "elements": [
            {
                "id": "login;login-with-valid-admin-user-credentials",

This causes issue with reporter.
Also I observed that jsonmerge is eliminating repeated elements based on id.

**Comment by thyagab** [comment]
@gkushang any update?

**Comment by gkushang** [comment]
@thyagab can you provide sample JSON to try it out?

**Comment by thyagab** [comment]
@gkushang please find attached json output generated.

[Archive.zip](https://github.com/gkushang/cucumber-html-reporter/files/445472/Archive.zip)

**Comment by gkushang** [comment]
https://github.com/gkushang/cucumber-html-reporter/pull/12 adds the support for multi capabilities thru `jsonDir` option

**Comment by gkushang** [comment]
published cucumber-html-reporter@0.2.8

**Comment by thyagab** [comment]
Thank you @gkushang for fixing it.

**Comment by thyagab** [comment]
@gkushang is it possible to add a option to ignore invalid json files?
We have a case where protractor is generating a blank json file for feature files with tagging.
