### ISSUE TITLE
time taken for scenarios is showing strange values 

### ISSUE THREAD

**Issue by kchamberlain** [gkushang/cucumber-html-reporter#94]
![cucumber time](https://user-images.githubusercontent.com/28895140/28019960-9b558958-657a-11e7-9496-a30b4c4926e3.PNG)

time duration for scenarios doesn't look right to me any ideas?
I'm running my tests from Jenkins, running all 267 tests, they all pass and it takes about 20 mins to run..
I also don't see a total time taken anywhere...

**Comment by gkushang** [comment]
It certainly looks incorrect. Could you let me know the versions of `cucumber`, `cucumber-html-reporter`? If possible, could you post the part of your JSON report?

**Comment by kchamberlain** [comment]
We’re using gulp
And in the package.JSon:

"cucumber": "^0.10.2",
"cucumber-html-reporter": "^2.0.0",

Have attached the report.json file

Many thanks
Kay

**Comment by gkushang** [comment]
Hi @kchamberlain 

Since you're using Cucumber's version `0.10.2`, please consider using `cucumber-html-reporter version 0.4.0`. Take a look at the installation instructions [here]. (https://github.com/gkushang/cucumber-html-reporter#install) 

Thanks!

**Comment by kchamberlain** [comment]
Hi
I’ve tried report version 0.4.0 and the times still look strange…

Kay

**Comment by gkushang** [comment]
Can you share your sample JSON file?

**Comment by jdvegmond** [comment]
Apparently the time in the json is in nanoseconds. https://groups.google.com/forum/#!topic/cukes/NhIwx1FrU1g

**Comment by gkushang** [comment]
@kchamberlain 

The nanoseconds are introduced in the report, please retest with the latest release  @4.0.3 and feel free to reopen the issue.

Thank you!
