### ISSUE TITLE
'Simple' template is missing 'moment' script

### ISSUE THREAD

**Issue by josepmc** [gkushang/cucumber-html-reporter#98]
When generating reports with the 'simple' template the 'moment' script is missing. That means, that the script is not imported in the template.

This is specially troublesome if using a browser (phantomjs, via html-pdf) to convert this html file into pdf, as it will throw an error and thus make it inviable to use without manual template modification.

The generated code is as follows:
```javascript
//  Update build time to since
    var buildTimeElem = document.getElementById("buildTime");
// The following line fails
    buildTimeElem.innerHTML = 'Built ' + moment(buildTimeElem.innerHTML).fromNow();
```

PS: As a feature suggestion, you could allow an external template to be provided.

**Comment by gkushang** [comment]
fixed & published with v3.0.1
